# Generated by Django 6.1 on 2026-08-19 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField()),
                ('vao', models.PositiveIntegerField()),
                ('codigo', models.CharField(help_text='Código do endereço. Ex: T01-N02-V03', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('LIVRE', 'Livre'), ('OCUPADA', 'Ocupada'), ('BLOQUEADA', 'Bloqueada')], default='LIVRE', max_length=10)),
                ('observacao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
                'ordering': ['torre__codigo', 'nivel', 'vao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('descricao', models.CharField(max_length=200)),
                ('unidade', models.CharField(default='UN', help_text='Unidade de medida. Ex: UN, CX, KG', max_length=10)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único da torre. Ex: T01', max_length=20, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('localizacao', models.CharField(blank=True, help_text='Setor/corredor onde a torre está localizada (opcional).', max_length=100)),
                ('qtd_niveis', models.PositiveIntegerField(help_text='Quantidade de níveis (andares) da torre.')),
                ('qtd_vaos', models.PositiveIntegerField(help_text='Quantidade de vãos (colunas) por nível.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Torre',
                'verbose_name_plural': 'Torres',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Palete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador do palete.', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('EXPEDIDO', 'Expedido')], default='ATIVO', max_length=10)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_expedicao', models.DateTimeField(blank=True, null=True)),
                ('posicao', models.OneToOneField(blank=True, help_text='Posição atual do palete. Vazio se estiver em trânsito/na doca.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palete_atual', to='estoque.posicao')),
            ],
            options={
                'verbose_name': 'Palete',
                'verbose_name_plural': 'Paletes',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('TRANSFERENCIA', 'Transferência'), ('SAIDA', 'Saída')], max_length=15)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('palete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.palete')),
                ('posicao_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='estoque.posicao')),
                ('posicao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='estoque.posicao')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ItemPalete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('validade', models.DateField(blank=True, null=True)),
                ('palete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.palete')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_palete', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Item do Palete',
                'verbose_name_plural': 'Itens do Palete',
            },
        ),
        migrations.AddField(
            model_name='posicao',
            name='torre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='estoque.torre'),
        ),
        migrations.AlterUniqueTogether(
            name='posicao',
            unique_together={('torre', 'nivel', 'vao')},
        ),
    ]
