# Generated by Django 6.1 on 2026-08-24 11:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='saldo_estoque',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo disponível para alocação em paletes.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='itempalete',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
