# Generated by Django 6.1 on 2026-08-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_saldo_estoque_alter_itempalete_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('UNIDADE', 'UNIDADE'), ('CAIXA', 'CAIXA'), ('KG', 'KG')], default='UNIDADE', help_text='Selecione a unidade de medida.', max_length=10),
        ),
    ]
