# Generated by Django 6.1 on 2026-08-24 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_produto_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempalete',
            name='quantidade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='saldo_estoque',
            field=models.PositiveIntegerField(default=0, help_text='Saldo disponível para alocação em paletes.'),
        ),
    ]
