# Generated by Django 6.1 on 2026-08-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_itempalete_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='saldo_estoque',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade total cadastrada em estoque.'),
        ),
    ]
