# Generated by Django 6.1 on 2026-08-24 11:38

from django.db import migrations
from django.db.models import Sum


def converter_para_saldo_total(apps, schema_editor):
    Produto = apps.get_model('estoque', 'Produto')
    ItemPalete = apps.get_model('estoque', 'ItemPalete')

    for produto in Produto.objects.all():
        alocado = (
            ItemPalete.objects.filter(produto_id=produto.id)
            .aggregate(total=Sum('quantidade'))
            .get('total')
            or 0
        )
        produto.saldo_estoque = produto.saldo_estoque + alocado
        produto.save(update_fields=['saldo_estoque'])


def noop_reverse(apps, schema_editor):
    # Não há conversão reversível confiável.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_produto_saldo_estoque'),
    ]

    operations = [
        migrations.RunPython(converter_para_saldo_total, noop_reverse),
    ]
