# Generated by Django 6.1 on 2026-08-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_converter_saldo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='setor',
            field=models.CharField(choices=[('GERAL', 'Geral'), ('BAC', 'Pos-vendas (BAC)')], default='GERAL', help_text='Setor responsável pelo palete.', max_length=10),
        ),
        migrations.AddField(
            model_name='posicao',
            name='setor_destino',
            field=models.CharField(choices=[('GERAL', 'Geral'), ('BAC', 'Pos-vendas (BAC)')], default='GERAL', help_text='Define se a posição é geral ou dedicada ao setor BAC.', max_length=10),
        ),
    ]
